{
  "formatVersion": "1.1",
  "component": {
    "group": "com.id365.idverification",
    "module": "sdk",
    "version": "2.1.16",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.4"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.grpc",
          "module": "grpc-protobuf-lite",
          "version": {
            "requires": "1.51.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-kotlin-stub",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-kotlin-lite",
          "version": {
            "requires": "3.19.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-2.1.16.aar",
          "url": "sdk-2.1.16.aar",
          "size": 1815602,
          "sha512": "7a1ad1352e69d05f54190bb4e697689deb4a7c550b01feb399bdfbd89458a550a184a66ee93c4c123f121013d224369d2aae746390428530d6aff6ff696a0127",
          "sha256": "bf174c2fd2f7a9cec509c3e97c5b20280280211bdc959907e14c4fa17d82b5a9",
          "sha1": "dad88de94acd37e78f556df4245a9d7148d9a921",
          "md5": "4157e94db876eee33cd1fe181cc2cd3c"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "6.29.0"
          }
        },
        {
          "group": "com.microblink",
          "module": "capture-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-themeadapter-appcompat",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-insets",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-systemuicontroller",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-okhttp",
          "version": {
            "requires": "1.51.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.1.6"
          }
        },
        {
          "group": "com.iproov.sdk",
          "module": "iproov",
          "version": {
            "requires": "9.0.2"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf-lite",
          "version": {
            "requires": "1.51.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-kotlin-stub",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-kotlin-lite",
          "version": {
            "requires": "3.19.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.3.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-2.1.16.aar",
          "url": "sdk-2.1.16.aar",
          "size": 1815602,
          "sha512": "7a1ad1352e69d05f54190bb4e697689deb4a7c550b01feb399bdfbd89458a550a184a66ee93c4c123f121013d224369d2aae746390428530d6aff6ff696a0127",
          "sha256": "bf174c2fd2f7a9cec509c3e97c5b20280280211bdc959907e14c4fa17d82b5a9",
          "sha1": "dad88de94acd37e78f556df4245a9d7148d9a921",
          "md5": "4157e94db876eee33cd1fe181cc2cd3c"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "sdk-2.1.16-sources.jar",
          "url": "sdk-2.1.16-sources.jar",
          "size": 413387,
          "sha512": "80ea4a1e73855ed0b3dc6967db3101a6eff1ea6fe6ee31ab7c23ee6c71877c9b140b5627f579d4c158dee29d9c3483bad6c8f4ea433c7f18462a15db26eb5ee5",
          "sha256": "fa6da3ff13a86adc30e415da1c53a63751b1a67dd3b837d1ac72326b850d3dc9",
          "sha1": "5a16eef5187a38b1e9c43701316709847207ad50",
          "md5": "bfc9683dd59c092ab11e9c374b81ec24"
        }
      ]
    }
  ]
}
