{
  "formatVersion": "1.1",
  "component": {
    "group": "com.id365.idverification",
    "module": "sdk",
    "version": "2.5.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.grpc",
          "module": "grpc-protobuf-lite",
          "version": {
            "requires": "1.51.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-kotlin-stub",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-kotlin-lite",
          "version": {
            "requires": "3.19.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.7.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.7.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.7.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-2.5.6.aar",
          "url": "sdk-2.5.6.aar",
          "size": 2115298,
          "sha512": "0b14b5517758ef080d53a6235316bdd6fa6546399ac5c047b0b579680c6d80ec84a20e0a23ce00d2d434e647cc75c206235386e57061ed26b7e9efee3b400cc7",
          "sha256": "6e2952ffd80a74fdcd6004918748f4cac16975622ff4e043a517a680914c27ca",
          "sha1": "e6fc6b2113c844d287ecaa9baee658539756636f",
          "md5": "e7caf5ad9deb521cc287f8907735d651"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "com.microblink",
          "module": "capture-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-themeadapter-appcompat",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-insets",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-systemuicontroller",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-okhttp",
          "version": {
            "requires": "1.51.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.38.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.38.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.38.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-extension-autoconfigure",
          "version": {
            "requires": "1.38.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.1.6"
          }
        },
        {
          "group": "com.iproov.sdk",
          "module": "iproov",
          "version": {
            "requires": "10.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf-lite",
          "version": {
            "requires": "1.51.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-kotlin-stub",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-kotlin-lite",
          "version": {
            "requires": "3.19.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.7.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.7.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.7.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-2.5.6.aar",
          "url": "sdk-2.5.6.aar",
          "size": 2115298,
          "sha512": "0b14b5517758ef080d53a6235316bdd6fa6546399ac5c047b0b579680c6d80ec84a20e0a23ce00d2d434e647cc75c206235386e57061ed26b7e9efee3b400cc7",
          "sha256": "6e2952ffd80a74fdcd6004918748f4cac16975622ff4e043a517a680914c27ca",
          "sha1": "e6fc6b2113c844d287ecaa9baee658539756636f",
          "md5": "e7caf5ad9deb521cc287f8907735d651"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "sdk-2.5.6-sources.jar",
          "url": "sdk-2.5.6-sources.jar",
          "size": 484527,
          "sha512": "088e73b052603d393b8d7e75c9b7848365646d93f1afe5c93a0e44d5e02ddea61d324035cafd4fd38f36585fec024fe8cb0ab9695660a36842aa7375541687ba",
          "sha256": "35b1d12cbe50c2ad0e40804746b52fe86805f495c1823947d1a9742a4acff3bf",
          "sha1": "8fdb2b1bc3fe6806c7417d731bec04887075cf63",
          "md5": "efb0d2ed59c0079ea2141c8dfbb44d5f"
        }
      ]
    }
  ]
}
