{
  "formatVersion": "1.1",
  "component": {
    "group": "com.id365.idverification",
    "module": "sdk",
    "version": "2.5.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.grpc",
          "module": "grpc-protobuf-lite",
          "version": {
            "requires": "1.51.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-kotlin-stub",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-kotlin-lite",
          "version": {
            "requires": "3.19.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.7.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.7.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.7.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-2.5.4.aar",
          "url": "sdk-2.5.4.aar",
          "size": 2103333,
          "sha512": "56807ce040a0afd58dc1c794e2679be4439c3d9cdb70098853f84c1186ff553e1665854594749284bc26f6373a26b213191e13a764cfa7278ad380e92fd58315",
          "sha256": "69178d9c5377aa05cdcca87cc31302a6f8b7ef6e7b94c9c4a9d5f049bd42455b",
          "sha1": "a25ef8774299b005bf7d411169bc2fe3232ededa",
          "md5": "e0f1f2080db37fb2211a5d82fe1ab977"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "com.microblink",
          "module": "capture-core",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.3.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-themeadapter-appcompat",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-insets",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-systemuicontroller",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.7.6"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.3.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-okhttp",
          "version": {
            "requires": "1.51.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-api",
          "version": {
            "requires": "1.38.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk",
          "version": {
            "requires": "1.38.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-exporter-otlp",
          "version": {
            "requires": "1.38.0"
          }
        },
        {
          "group": "io.opentelemetry",
          "module": "opentelemetry-sdk-extension-autoconfigure",
          "version": {
            "requires": "1.38.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.1.6"
          }
        },
        {
          "group": "com.iproov.sdk",
          "module": "iproov",
          "version": {
            "requires": "10.4.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.8.8"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf-lite",
          "version": {
            "requires": "1.51.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-kotlin-stub",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-kotlin-lite",
          "version": {
            "requires": "3.19.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.7.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.7.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.7.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.7.3"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.25"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-2.5.4.aar",
          "url": "sdk-2.5.4.aar",
          "size": 2103333,
          "sha512": "56807ce040a0afd58dc1c794e2679be4439c3d9cdb70098853f84c1186ff553e1665854594749284bc26f6373a26b213191e13a764cfa7278ad380e92fd58315",
          "sha256": "69178d9c5377aa05cdcca87cc31302a6f8b7ef6e7b94c9c4a9d5f049bd42455b",
          "sha1": "a25ef8774299b005bf7d411169bc2fe3232ededa",
          "md5": "e0f1f2080db37fb2211a5d82fe1ab977"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "sdk-2.5.4-sources.jar",
          "url": "sdk-2.5.4-sources.jar",
          "size": 484134,
          "sha512": "1850c66b52c818292a3a96a871805fc1e1267b85a527d7ca2610fec83514630eb3209c46752960917ad8cc9bb559095db7e584420d4d60f87e11be3c4ebbd5f3",
          "sha256": "ec71163971925954ee95ccbbc6d17de4df7402ca901691524c1aa1597674f697",
          "sha1": "3deaa17348e18ff47f08dbd42ea625b5eb49281e",
          "md5": "cf94c351f35ed42d1a1214fc4e830721"
        }
      ]
    }
  ]
}
