{
  "formatVersion": "1.1",
  "component": {
    "group": "com.id365.idverification",
    "module": "cv",
    "version": "1.1.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "cv-1.1.9.aar",
          "url": "cv-1.1.9.aar",
          "size": 13625226,
          "sha512": "f6fd4a9663c091a0f1aef2aa7cdc824d53cff5c1d68621df43fca7ddcc958e37cb8c6ac6002f72ad87391e6459223ac0e38a8f3ae1742929159489e02b87cad9",
          "sha256": "df7ea13c2bff471de1e629509f857dcec1024627d5a714b93957612dbfac76f3",
          "sha1": "cba07187d4f4d2b29b2e66444e552e467696206f",
          "md5": "93661f5312b43222b51e4faebbc214f1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        }
      ],
      "files": [
        {
          "name": "cv-1.1.9.aar",
          "url": "cv-1.1.9.aar",
          "size": 13625226,
          "sha512": "f6fd4a9663c091a0f1aef2aa7cdc824d53cff5c1d68621df43fca7ddcc958e37cb8c6ac6002f72ad87391e6459223ac0e38a8f3ae1742929159489e02b87cad9",
          "sha256": "df7ea13c2bff471de1e629509f857dcec1024627d5a714b93957612dbfac76f3",
          "sha1": "cba07187d4f4d2b29b2e66444e552e467696206f",
          "md5": "93661f5312b43222b51e4faebbc214f1"
        }
      ]
    }
  ]
}
