{
  "formatVersion": "1.1",
  "component": {
    "group": "com.id365.idverification",
    "module": "sdk",
    "version": "2.1.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "io.grpc",
          "module": "grpc-protobuf-lite",
          "version": {
            "requires": "1.51.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-kotlin-stub",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-kotlin-lite",
          "version": {
            "requires": "3.19.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-2.1.7.aar",
          "url": "sdk-2.1.7.aar",
          "size": 1719196,
          "sha512": "56dc6fea3b75279f5be45c4c773036ea6cb262f8d9d002131edd3cb0c5bcdc3c9cc75df810cea48eeeaee4c8fc72381406d250aef3d6559fafa36f0f2a680451",
          "sha256": "031e87c66e11823347d3b5e946d5744156b3859a585ca928b17dc5efe213890f",
          "sha1": "457b7f1ab9f2f93dd96389e218c9ceb2fea51995",
          "md5": "b624e7b727752c788cb978f1120c0abf"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "io.sentry",
          "module": "sentry-android",
          "version": {
            "requires": "6.29.0"
          }
        },
        {
          "group": "com.microblink",
          "module": "capture-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.6.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-livedata-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.material",
          "module": "material",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.animation",
          "module": "animation",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-themeadapter-appcompat",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-insets",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-systemuicontroller",
          "version": {
            "requires": "0.28.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview",
          "version": {
            "requires": "1.5.4"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-view",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.mlkit",
          "module": "barcode-scanning",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-okhttp",
          "version": {
            "requires": "1.51.0"
          }
        },
        {
          "group": "io.insert-koin",
          "module": "koin-android",
          "version": {
            "requires": "3.1.6"
          }
        },
        {
          "group": "com.iproov.sdk",
          "module": "iproov",
          "version": {
            "requires": "9.0.2"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf-lite",
          "version": {
            "requires": "1.51.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-kotlin-stub",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-kotlin-lite",
          "version": {
            "requires": "3.19.2"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-common",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-runtime",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-adapters",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "databinding-ktx",
          "version": {
            "requires": "8.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-2.1.7.aar",
          "url": "sdk-2.1.7.aar",
          "size": 1719196,
          "sha512": "56dc6fea3b75279f5be45c4c773036ea6cb262f8d9d002131edd3cb0c5bcdc3c9cc75df810cea48eeeaee4c8fc72381406d250aef3d6559fafa36f0f2a680451",
          "sha256": "031e87c66e11823347d3b5e946d5744156b3859a585ca928b17dc5efe213890f",
          "sha1": "457b7f1ab9f2f93dd96389e218c9ceb2fea51995",
          "md5": "b624e7b727752c788cb978f1120c0abf"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "sdk-2.1.7-sources.jar",
          "url": "sdk-2.1.7-sources.jar",
          "size": 431238,
          "sha512": "2517858d582a5615bce311e6a8f557acdc12ca7e6536bcf21486fd532c818586e42a13244b8ac9f5ee4a5024c3e12df5d5c36ac9a46be02acbeba3529cb48c23",
          "sha256": "6b0835aeb140849769afa18c1853613e8e5ac0b30be89b8bffaba2f774e77607",
          "sha1": "5dfdee1cc7bcd70476f37bdd9caf01f3001de1a4",
          "md5": "4cda1bbf4a32cc33208e5b677933d355"
        }
      ]
    }
  ]
}
